### ISSUE TITLE
allow installation of Microsoft Teams

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1149]
## Background Information

From [Trello card](https://trello.com/c/hvX9X6rT/247-package-microsoft-teams):

> Just learned that [Teams is approved in GEAR](https://ea.gsa.gov/#!/itstandards/2407), and a number of TTS members use it for collaborating with other agencies. Would be helpful for it to be easily installable, particularly without admin.

## Implementation Steps

See card.

## Acceptance Criteria

- [x] People that need Teams have a clear path to install the app

**Comment by its-a-lisa-at-work** [comment]
Generally ... looks good!

Nit-picky...
Current Acceptance Criteria isn't 'testable' in the sense of "if someone looks back to determine if this was met, would they be able to" recommend tweaking it a little bit to say something like
- [ ] TTS provides updated instructions in handbook related to new availability of Teams software

I believe there is also a usecase here to test out the Software Concierge process since the tool should also be listed on our internal spreadsheet. cc: @melanienleopold 

Also, the implementation steps listed in the Trello card it isn't obvious which steps the TTS Tech Representative should be responsible, accountable, consulted, supported or informed for.

**Comment by afeld** [comment]
Complete.
