### ISSUE TITLE
GitHub ATO renewal

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1249]
## Background Information

Github ATO needs to be renewed

## Implementation Steps
- [x] Figure out steps required

## Acceptance Criteria

- [x] ATO has been renewed

**Comment by josephderosales** [comment]
No response received from Tamara - reached out to Nate Ciano - ISTE <nathaniel.ciano@gsa.gov>

Awaiting response.....

**Comment by josephderosales** [comment]
FROM TAMARA:

GitHub Enterprise can be deployed as self-hosted, cloud, or hybrid.
The Cloud deployment is FedRAMP Tailored and the self-hosted version is the one in GEAR.  
 
The self-hosted version is listed in GEAR and I don't have any insight into if that ATO date is correct or not.  I'm not sure where the date would have even come from.

The LI-SaaS version does NOT have a GSA ATO - it was on the list to get done with TTS but now needs someone else to be the tech contact and do the drawings/controls for the CRM package.  I had Alyssa as the contact that now needs a new person.  If there is someone else that wants to take a shot at the SSP, I have it ready for technical input - just need to know who to send the template to.

It comes down to where the users are putting their data.  If they are putting it in the cloud, it's SaaS and absolutely does not have a GSA ATO.  If they are using on-prem servers, it's under the GEAR entry and I don't have insight into how the ATO date for that was determined.

**Comment by josephderosales** [comment]
[GitHub GSA Implementation_SSP.docx](https://github.com/18F/tts-tech-portfolio/files/6183342/GitHub.GSA.Implementation_SSP.docx)

**Comment by josephderosales** [comment]
Email sent to GSA-IT GitHub Admins:

Hello GitHub Support/Admins,

IT Security has made our office aware that the GitHub GSA CRM SSP (attached) must be completed. Some portions of the documentation has already been populated. 

GEAR currently reflects GitHub with an expired ATO of 3/30/2020. In order to establish a new ATO date and maintain security compliance, the required documentation must be completed and submitted to IT Security ASAP. 

Is there someone from your office that can review and complete the necessary documentation? Thank you.

**FROM GERARD CHELAK**
We will review this request and get back to you as soon as possible.  Thank you.

**Comment by josephderosales** [comment]
From Tamara: The SSP is in Docusign pending signature now.  Once it is signed by everyone, I'll draft the cert memo and Richard Adarkwa will add it to IC-EAS.

**Comment by afeld** [comment]
Mind sending to devops@gsa.gov so we can see what's in there?

**Comment by josephderosales** [comment]
The ATO date for GitHub is March 25, 2023. The SSP has been signed as well. GEAR update in-progress.

**Comment by afeld** [comment]
Mind getting us access / a copy?

**Comment by josephderosales** [comment]
@afeld I just requested access to both the signed SSP and ATO. Will share once I receive it.

**Comment by josephderosales** [comment]
^^^^ GitHub CRM
https://drive.google.com/file/d/1Y1x8H8kMOztB4R9n4r1_UkduGSoYGfRu/view?ts=609d5293
