### ISSUE TITLE
convert tts-bot to a GitHub App

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#1480]
## Background Information

Having a single user with a shared password is not ideal; I think the things @tts-bot does _should_ be doable from a [GitHub App](https://docs.github.com/en/developers/apps/getting-started-with-apps/about-apps), and can be managed more centrally.

## Implementation Steps

- [ ] 

## Acceptance Criteria

- [ ] @tts-bot user no longer needed (deleted?)

**Comment by adborden** [comment]
Here's my 30-minute assessment: this is days to weeks of effort, and we'd have to put in a little effort to come up with a solution that meets the needs of the various places we want to leverage the app (e.g. CircleCI, GH Actions, Terraform, etc). First, we'd want to confirm if the GitHub server-to-server token that you get from the App is compatible where personal access tokens are used. IMHO GitHub seems to push you to use personal access tokens for our use cases and implementing a GitHub App as a script introduces more complexity (and potential risk) than the lesser privilege it might provide.

From the [About apps](https://docs.github.com/en/developers/apps/getting-started-with-apps/about-apps) on GitHub:
> GitHub Apps are applications that need to be hosted somewhere. For step-by-step instructions that cover servers and hosting, see "Building Your First GitHub App."

Usually that means a web application, but you should be able to write a script that is run via CI. There doesn't seem to be any official documentation on writing an App as a script, but there are [some blogs with sample code](https://www.jerriepelser.com/blog/obtain-access-token-github-app-webhook/). The relevant official docs should be covered under [Authenticating as an Installation](https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps#authenticating-as-an-installation). Overall it involves:

1. [Install the app on your repositories](https://docs.github.com/en/developers/apps/managing-github-apps/installing-github-apps)
1. Create and sign a JSON Web Token (JWT)
2. Fetch the list of installations
3. [Get an access token for a specific installation](https://docs.github.com/en/rest/reference/apps#create-an-installation-access-token-for-an-app)
4. Use the GitHub server-to-server token in place of a personal access token

[GitHub recently updated their tokens](https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/) and it's important to note that the token you get from the GitHub App is _not_ a personal access token. It's possible that as a security precaution, third-party applications or GitHub might check that the token is the correct type of token given its use. This is something we should verify (manually follow the steps to create a GH server-to-server token and use it in place of the personal access token).

Additionally, the access token doesn't have access to all APIs, [only this subset of endpoints are available](https://docs.github.com/en/rest/overview/endpoints-available-for-github-apps) so we should be conscious of what endpoints we need to access.

Because you need to distribute the private key where your app runs, the app has access to all installations. If you want least privilege access, you really need to create multiple GitHub Apps, each with its own private key.

Next steps:
1. Manually test generating the token and then test it where we're currently using tts-bot
2. Write a script/program/app that will output the token so the token can be a drop in where a personal access token is currently expected

**Comment by adborden** [comment]
This was briefly discussed in standup and we've decided not to proceed on this work.
