### ISSUE TITLE
document "How We Work"

### ISSUE THREAD

**Issue by its-a-lisa** [18F/tts-tech-portfolio#248]
## Background information
Looking to create our own version of this document: [Front-end Management
](https://docs.google.com/document/d/1L38IAJ9hI5wuRXxKa3fhGcaV607M5D6S_fr7qxntzkk/edit)
Other things to consider: 
[Leave instructions for 18F](https://github.com/18F/handbook/pull/1707)
[OOO procedures](https://docs.google.com/document/d/1qgA-vEQ1_t5plPCAs1aCOAjK0RXQzka2hHSVhoa6v5o/edit)
[18F How We Work](https://github.com/18F/handbook/tree/master/_pages/how-we-work)

## User stories

As someone new to the team, I would like detailed information on the specifics of how this team works. 

## Implementation

- [ ] Include page on OOO procedures specific to our team
- [ ] Link to the Project Board doc
- [ ] Move the tech portfolio onboarding/offboarding page to a doc in our repo

## Acceptance criteria

- document available for review 
- all members give a thumbs up!

**Comment by afeld** [comment]
[Extremely thorough example from Netflix](https://jobs.netflix.com/culture) via @its-a-lisa.

**Comment by afeld** [comment]
Dropping some proposed content here so I don't forget:

- We work 40 hours, no more, no less (minus [holidays](https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/) and [leave](https://handbook.tts.gsa.gov/leave/)). You are expected to be at meetings unless you let people know you can't, but otherwise, you can work whatever schedule is best for you.
- We respond to people (internally and externally) within one working day.
   - Work emergencies may mean you need to respond sooner, but these should be rare.

**Comment by its-a-lisa** [comment]
@afeld is this one that we can close in favor of #356 ?

**Comment by afeld** [comment]
This issue is more about stuff _around_ the workflow (philosophy, communication, etc.), so let's take care of it separately.

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
