### ISSUE TITLE
set up continuous integration/deployment of GitHub configuration

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#443]
## Background information

Right now, the Terraform state files are local for the following repositories:

Repo | Person with state file
--- | ---
aws-admin | [_already in the `tts-aws-admin` bucket_](https://github.com/18F/aws-admin/blob/6b2bf3d6a973a68922f4d3cf2bbbe70cd512070d/terraform/main.tf#L4)
newrelic-terraform | @JJediny 
tts-tech-portfolio | @afeld 

This means the listed person is the only one who can (easily) deploy changes. Given the setup is going to be similar for each, probably makes sense to do them all at the same time.

## User stories

- As someone wanting to make changes to labels, I don't want to be blocked deploying them.

## Implementation

- [x] Create Terraform backend(s)
   - Might make sense to split out and expand [this bootstrapping code](https://github.com/18F/aws-admin/tree/master/terraform/bootstrap), or see if there is an existing open source project that does the equivalent
   - Not sure if it makes sense to use the same bucket or one per repository
- [x] Set up continuous integration/deployment (CI/CD)
   - [x] ~aws-admin~ https://github.com/18F/aws-admin/issues/151
   - [x] ~newrelic-terraform~ https://github.com/18F/newrelic-terraform/issues/16
   - [x] tts-tech-portfolio
- [x] Add/update documentation in this repo, as necessary

## Acceptance criteria

- Any changes to Terraform on `master` run a `terraform apply`
- Any changes to Terraform on other branches run a `terraform plan`

**Comment by its-a-lisa-at-work** [comment]
Moving this to Backlog so that it gets completed in a sprint sooner than later since it is a blocker to #556

**Comment by afeld** [comment]
Let's (re?)narrow the scope of this to be for the GitHub configuration specifically. https://github.com/18F/tts-tech-portfolio/issues/467 is for AWS; let's make an equivalent for New Relic config.

**Comment by afeld** [comment]
We can split the creation of the backend from the continuous deployment if that helps break it down.

**Comment by its-a-lisa-at-work** [comment]
@afeld or @JJediny  did you end up splitting this card up?

**Comment by afeld** [comment]
Split out https://github.com/18F/tts-tech-portfolio/issues/778. That one is a blocker for continuous deployment.

**Comment by its-a-lisa-at-work** [comment]
@afeld can we please put a date on this? I feel like things shouldn't move to the icebox after they've already been Sprint Planned. And this is something that I feel strongly is a blocker for me doing Internal Workflow activity so would appreciate it if it gets done sooner rather than later; at least in the next 2 sprints, 3 at most.

**Comment by amitfreeman-gov** [comment]
I propose this ticket 

- Get's renamed so that it matches the scope of work (e.g. "Create terraform backends for repos with no shared state")
- Spawns different tickets for the CI/CD ask - it is not clear to me what the scope of work or the specific problem being addressed is, and the corresponding acceptance criteria neither clarifies nor checks it's acceptance.

**Comment by afeld** [comment]
Moved to Icebox since https://github.com/18F/tts-tech-portfolio/issues/778 is the actual blocker — this issue is a nice-to-have.

**Comment by adborden** [comment]
PRs merged, this is ✔️
