### ISSUE TITLE
consensus around what to do with missing attendees for internal meetings

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#569]
## Background information

When someone can't make it (planned or last-minute) to a meeting within the team, there's always uncertainty about whether to move it, cancel, or proceed without them. If the team were larger, presumably we'd proceed regardless, but there are only four of us. Would be nice to have some criteria/default to not have to think about it. Examples:

- As long as there are at least two people, proceed.
- If over [percentage] of the Tech Portfolio can't make it, try to reschedule for the following business day, or just cancel if that would be duplicative.

For simplicity, thinking we scope this to "internal meetings", meaning our sprint ceremonies or other meetings where it's expected that the full Tech Portfolio would be there.

## User stories

- As someone running an internal meeting, I want to know what to do when people can't attend.
   - Maybe there's a percent quorum or something?

## Acceptance criteria

- Documented decision criteria for what to do with meetings that one or more people can't attend

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
@afeld looking at the current acceptance criteria` If one or more people can't attend a given meeting, it doesn't take any thought to know what to do with the meeting` I almost feel like that is a part of a user story rather than acceptance criteria. 

I feel like a question to help prompt with acceptance criteria is "what would it take for this issue to be done" and I think the way it is currently written makes it hard to come up with implementation steps.

**Comment by its-a-lisa-at-work** [comment]
Moving back to Backlog until it is groom accepted.

**Comment by afeld** [comment]
Reworded. Better?

**Comment by its-a-lisa-at-work** [comment]
Yup, thanks!

**Comment by its-a-lisa-at-work** [comment]
Moving to Feedback/Waiting until #627 is merged
