### ISSUE TITLE
figure out strategy for upcoming ATOs

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#653]
## Background information

We have a handful of systems that will need assessment "soon":

- challenge.gov - ?
- data.gov - current ATO expires in March, and they worry about the (staff) cost of running in two environments until then
- Touchpoints - LATO extension expires 9/27

Unfortunately, we were told that the assessment calendar is booked until January. Given the previous success and efficiency of the [ATO Sprinting Team](https://18f.gsa.gov/2018/07/19/taking-the-ato-process-from-6-months-to-30-days/), I strongly believe we should re-institute it.

[Notes from previous meeting about this](https://docs.google.com/document/d/1Zk1YP4wCPV0uN6A0VCEj8pgsMTfqBSMAvAKzv0JVNoc/edit)

## User stories

- As a GSA system owner, I need authorization to launch / continue operating my system so that I can serve my users, and have various considerations that make the timing of that important.

## Acceptance criteria

- [ ] We have consensus with Security about how to handle these upcoming authorizations

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
- Acuant COFRS - expires 9/16
- analytics.usa.gov - expires 9/30

**Comment by cmhughes29** [comment]
Team - Wanted to note, while the assessment schedule backlog is the topic of discussion, some of the systems cited also aren't necessarily prepared for an assessment. Touchpoints for example still has quite a bit of work to do on their SSP per speaking with the ISSO.

**Comment by its-a-lisa-at-work** [comment]
Mind if we keep this in the Backlog? I think things that are already Sprint Planned for shouldn't go back into Icebox so they stay as something that gets picked up as soon as possible.

**Comment by afeld** [comment]
- AI Use Case Library - ?

**Comment by afeld** [comment]
- Tock - ?

**Comment by its-a-lisa-at-work** [comment]
Put a time on the calendar with Joseph Hoyt to talk through this on 11/16; moving to Backlog until then

**Comment by its-a-lisa-at-work** [comment]
me and @jhoyt22 have spoken about this a few time and reviewing the [TTS System Assessment Schedule](https://docs.google.com/spreadsheets/d/19wyA91KhGoZvnAA0fihC0WF_mU79YLRTHzDd-Frs8Qs/edit#gid=0) has become a regular part of our biweekly meetings. We have a good handle on the current systems and don't feel like anything is really at risk, the hard part will be fitting in systems that are newer -- in order to accurately be able to do that, we need to have an understanding of [when they need/want the system](https://github.com/18F/tts-tech-portfolio/issues/1075) to be in production by so I am going to reach out to the programs to get an understanding of this info.
