### ISSUE TITLE
Decide on having a TTS Software Concierge within the TTS Tech Portfolio

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/tts-tech-portfolio#742]
## Background information

Follow up from: https://github.com/18F/tts-tech-portfolio/issues/658 as mentioned in https://docs.google.com/document/d/1NC736hj2JEUSorC-JnjUeCFj9b9WLvbibRRIlZYuIG0/edit?ts=5f08ac12#bookmark=id.sv743vhn1e3

Related to #741 but different acceptance criteria; 

#741 will be blocked by this until this is completed

## Acceptance criteria

- [x] Made a decision that we will have a person dedicated to the intake of Software Requests
- [x] Decided that software request should flow through the TTS Tech Portfolio prior to getting requested to GSA IT

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
I'm leaning towards "this would be nice, but it doesn't feel realistic to commit any more time to it than is strictly necessary." cc @josephderosales

**Comment by its-a-lisa-at-work** [comment]
@afeld assigning to you based on the All-Hands today; seems like we decided we'd have a person, but still unsure of who that person should be

**Comment by afeld** [comment]
[Notes from All Hands](https://docs.google.com/document/d/1hmjgSZXLXcY7pvS-0R-7dkp4zmzykgt9Pv3YRCHgECc/edit#heading=h.2r3u4hvjj1tt)

@melanienleopold volunteered to be the person! A particularly good fit, since she's so involved in new software requests from the acquisition side anyway. Melanie, want to do the following?

- [ ] Create follow-up issues
- [ ] Write out some goals, and a roadmap if it makes sense to do things in stages
   - A first draft is fine; we can refine the two of us, or with that full group
- [ ] A kickoff meeting with @its-a-lisa-at-work @josephderosales @CinnyaSm and myself

**Comment by afeld** [comment]
- [ ] Add to the [roles](https://github.com/18F/tts-tech-portfolio/blob/master/how_we_work/roles.md)
