### ISSUE TITLE
get added as admins to TTS GitHub organizations

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#83]
## Background information

Want to get admin permissions on repositories on [these GitHub organizations](https://handbook.18f.gov/github/#organizations), either through an Owner role or at least a team with admin permissions.

cc #55 

## User stories

- As someone responsible for offboarding GitHub users, I want to have the access necessary to do so.

## Acceptance criteria

@tts-bot and the other Tech Portfolio members who go on OpsRotation are Owners on the following Organizations:

- [x] @18F
- [x] @digital-analytics-program
- [ ] @digitalgov
- [ ] @federalist-users
- [ ] @fedramp
- [x] @fellows-in-innovation
- [x] @GSA
- [x] @GSA [search.gov repos](https://docs.google.com/spreadsheets/d/1x7rI_zLtvoWLXbxu1z0RLdINPr5tMKZkGkFCFfcXa7s/edit#gid=0)
- [x] @project-open-data
- [x] @presidential-innovation-fellows
- [x] @usagov
- [x] @uswds 

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
@hoaiandang did you have a reason for not 👍 or was it because you didn't see it?

I went back and provided a 👍 ; when I first read it the acceptance criteria was unclear to me, but it is clear now. 

I would also suggest removing the specific names and say "All-members of the TTS Tech Portfolio" since that can accommodate for folks on-boarding in prior to this card being finalized.

**Comment by afeld** [comment]
> I would also suggest removing the specific names

Made it a bit more general.
